export const OBJ_ACCION_CARGA_PUBLICACIONES = "OBJ_ACCION_CARGA_PUBLICACIONES";
export const OBJ_ACCION_CARGA_USUARIO = "OBJ_ACCION_CARGA_USUARIO";
export const OBJ_ACCION_CARGA_AMIGOS = "OBJ_ACCION_CARGA_AMIGOS";
export const OBJ_ACCION_ADICIONAR_ERROR = "OBJ_ACCION_ADICIONAR_ERROR";
export const OBJ_ACCION_REMOVER_ERROR = "OBJ_ACCION_REMOVER_ERROR";
export const OBJ_ACCION_ERROR = "OBJ_ACCION_ERROR";